name: tick_conda_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc=0.11.*
  - multiqc=1.6
  - cutadapt=3.0
  - r-base=4.0.*
  - r-tidyverse=1.3.*
  - r-openxlsx=4.2.*
  - bioconductor-dada2=1.18.*
  - blast=2.10.*
