name: tick_conda_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.12
  - bioconda::cutadapt=3.5
  - conda-forge::r-base=4.1.2
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-openxlsx=4.2.5
  - conda-forge::r-readxl=1.3.1
  - conda-forge::r-dt=0.20 
  - bioconda::bioconductor-dada2=1.22.0
  - bioconda::blast=2.12.*
